buildtestandpush:
  script:
    - for i in `ls *.md`; do name=$(echo $i | cut -f 1 -d '.') && pandoc -s $i -o $name.html ; done
    - aws configure set aws_access_key_id $AWS_key
    - aws configure set aws_secret_access_key $AWS_secret
    - aws configure set region $AWS_region
    - aws s3 sync . s3://handbook.ngd.io --exclude="*" --include="*.html" --include="*.png" --region="eu-west-1"
  only:
    - master
