buildtestandpush:
  script:
    - echo '[default] / aws_access_key_id = $AWSAccessKey \ aws_secret_access_key = $AWSSecretKey \ region = eu-west1' >> .aws/credentials
    - for i in `ls *.md`; do name=$(echo $i | cut -f 1 -d '.') && pandoc -s $i -o $name.html ; done
    - cat .aws/credentials
  only:
    - master
